CREATE SEQUENCE SQ_GRUP_GRUPO start with 1 increment by 1;

INSERT INTO TB_GRUPO (SQ_GRUP_GRUPO, NM_GRUP_GRUPO) VALUES (SQ_GRUP_GRUPO.nextval, 'Grupo 1');
INSERT INTO TB_GRUPO (SQ_GRUP_GRUPO, NM_GRUP_GRUPO) VALUES (SQ_GRUP_GRUPO.nextval, 'Grupo 2');
INSERT INTO TB_GRUPO (SQ_GRUP_GRUPO, NM_GRUP_GRUPO) VALUES (SQ_GRUP_GRUPO.nextval, 'Grupo 3');
INSERT INTO TB_GRUPO (SQ_GRUP_GRUPO, NM_GRUP_GRUPO) VALUES (SQ_GRUP_GRUPO.nextval, 'Grupo 4');
